fix: remove unused dependencies and move dev dependencies
sass/embedded-host-node pull request #165
Opened 2022-09-06 14:16 UTC by alan-agius4

This change removes unused dependencies `semver` and `google-protobuf`. And moves development only dependencies `extract-zip`, `shelljs`, `tar`,  `yaml` and `make-fetch-happen` to `devDependencies`

2022-09-06 22:16 UTC, nex3 approved these changes

2022-09-06 22:16 UTC, nex3 commented
Thanks!

2022-09-07 00:00 UTC, nex3 requested changes
Looks like `google-protobuf` is still required at runtime.

2022-09-07 06:39 UTC, alan-agius4 commented
Oops. re-added.

2022-09-13 20:18 UTC, merged