Implement access tracking for containingUrl
sass/embedded-host-node pull request #285
Opened 2024-04-12 04:16 UTC by ntkme

https://github.com/sass/sass/pull/3835
https://github.com/sass/dart-sass/pull/2220

2024-04-12 16:04 UTC, ntkme commented
Looks like yesterday's node [20.12.2](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.12.2) is breaking our test on windows: https://github.com/nodejs/node/commit/69ffc6d50d

2024-04-12 17:29 UTC, ntkme commented
@nex3 I added a commit to fix the node regression.

Regarding CVE-2024-27980:
- `sass-embedded >=1.59.2` is not affected because in production release we always launch the `dart.exe` directly in production release since this commit: https://github.com/sass/embedded-host-node/commit/308862033e00f7a28a83c3114941efb053c395f6
- `sass-embedded <1.59.2` would be broken if a windows user upgrades to the latest node. There is no security risk for `sass-embedded` itself even if a windows user does not upgrade node, because we don't have any arguments when launching `.bat`, thus there is no risk of injection.
- Test is broken because we use the `.bat` wrapper in the test.

2024-04-12 22:55 UTC, nex3 commented
Can you pull the CVE fix into a separate PR?

2024-04-12 23:09 UTC, ntkme commented
@nex3 Created a separate PR for the CVE: https://github.com/sass/embedded-host-node/pull/286

2024-04-12 23:17 UTC, nex3 requested changes

2024-04-12 23:26 UTC, ntkme commented on lib/src/importer-registry.ts
> +  containingUrlAccessed = false;
Updated. I also made the same change for ArugmentList, which is where I copied the pattern.

2024-04-13 00:46 UTC, nex3 approved these changes

2024-04-17 21:33 UTC, merged