Fix error with deprecation warnings and legacy importers
sass/embedded-host-node pull request #339
Opened 2024-10-15 20:34 UTC by jathak

See https://github.com/sass/dart-sass/pull/2282.

2024-10-15 20:36 UTC, ntkme requested changes

2024-10-15 20:36 UTC, ntkme commented on lib/src/legacy/utils.ts
> +    url: URL.canParse(url)
`URL.canParse` requires `node >= 19.9.0`, so better do a `try` - `catch` instead.

2024-10-15 23:07 UTC, nex3 requested changes

2024-10-15 23:07 UTC, nex3 commented on lib/src/legacy/utils.ts
> +    return {...span, url: new URL(url, `file://${process.cwd()}`)};
Just shoving a pathname into a URL string isn't safe in general. Use Node's [`pathToFileUrl()`](https://nodejs.org/api/url.html#urlpathtofileurlpath-options).

2024-10-15 23:07 UTC, nex3 commented on lib/src/legacy/utils.ts
> +  } catch (_) {
If the URL is absolute, it won't use the basename anyway, so you can just pass it in eagerly rather than catching this error.

2024-10-16 23:09 UTC, nex3 approved these changes

2024-10-17 00:04 UTC, merged