Add includedFiles to render output
sass/embedded-host-node pull request #76
Opened 2021-11-02 16:57 UTC by danieka

I don't know if this fits with your thoughts on how to return stuff from the compilation. I'm open to feedback and modifying the PR.

2021-11-18 21:29 UTC, Awjin requested changes

2021-11-18 21:29 UTC, Awjin commented on lib/src/compile.test.ts
> +        expect(await compileString({source: 'a {b: c}'})).toMatchObject({
`toMatchObject` is too permissive here, let's use the stricter `toEqual` instead. (same for the other tests below)

```suggestion
        expect(await compileString({source: 'a {b: c}'})).toEqual({
```

2021-11-18 21:29 UTC, Awjin commented on lib/src/compile.ts
> +type CompileResult = {
```suggestion
export type CompileResult = {
```

Could you also export this from `lib/index.ts` so that it becomes part of the top-level API?

2021-11-18 21:29 UTC, Awjin commented on lib/src/compile.test.ts
>        // TODO(awjin): outputs in expanded mode explicitly
Please also add a test for a compilation that has `includedUrls` in the result.

2021-11-18 21:29 UTC, Awjin commented on lib/src/node-sass/render.ts
> +  const includedFiles = loadedUrls.map(url => url.replace('file://', ''));
This needs to handle file URLs properly on Windows, too.

```suggestion
  const includedFiles = loadedUrls.map(url => {
    return url.startsWith('file://') ? fileURLToPath(url) : url;
  });
```

2022-01-19 13:13 UTC, danieka commented
I'm sorry I never got around to finishing this, as far as I can tell it has already been implemented since the I made this PR so I'm going to close it. Super excited about the progress you're making @nex3 @Awjin! Thank you 😄

2022-01-19 13:13 UTC, closed without merging